# Generated by Django 5.2.5 on 2025-09-15 03:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3498db', max_length=7)),
                ('icon', models.CharField(default='receipt', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
            },
        ),
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('401k', '401(k)'), ('ira', 'IRA'), ('roth_ira', 'Roth IRA'), ('brokerage', 'Brokerage Account'), ('savings', 'Savings Account'), ('cd', 'Certificate of Deposit'), ('other', 'Other')], max_length=50)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('initial_investment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=3000, max_digits=12)),
                ('target_daily_spending', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('savings_goal', models.DecimalField(decimal_places=2, default=500, max_digits=12)),
                ('risk_tolerance', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], default='moderate', max_length=20)),
                ('investment_horizon', models.CharField(choices=[('short_term', '1-3 years'), ('medium_term', '3-10 years'), ('long_term', '10+ years')], default='long_term', max_length=20)),
                ('age', models.PositiveIntegerField(default=35)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('budget', 'Budget Optimization'), ('investment', 'Investment Strategy'), ('savings', 'Savings Strategy'), ('debt', 'Debt Management'), ('expense', 'Expense Reduction'), ('general', 'General Financial Advice')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('estimated_impact', models.CharField(choices=[('low', 'Low Impact'), ('medium', 'Medium Impact'), ('high', 'High Impact')], default='medium', max_length=50)),
                ('estimated_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_implemented', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_implemented', 'is_dismissed'], name='core_aireco_user_id_0c5198_idx'), models.Index(fields=['recommendation_type'], name='core_aireco_recomme_2277bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('description', models.TextField(blank=True)),
                ('merchant', models.CharField(blank=True, max_length=200)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('digital_wallet', 'Digital Wallet'), ('other', 'Other')], default='credit_card', max_length=50)),
                ('date', models.DateTimeField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.expensecategory')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='core_expens_user_id_84343e_idx'), models.Index(fields=['category'], name='core_expens_categor_974cef_idx'), models.Index(fields=['amount'], name='core_expens_amount_c8f245_idx')],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('alert_threshold', models.DecimalField(decimal_places=2, default=80.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.expensecategory')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='core_budget_user_id_72cb94_idx')],
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[('net_worth', 'Net Worth'), ('monthly_income', 'Monthly Income'), ('monthly_expenses', 'Monthly Expenses'), ('savings_rate', 'Savings Rate'), ('debt_to_income', 'Debt to Income Ratio'), ('credit_score', 'Credit Score'), ('other', 'Other')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'data_type', 'date'], name='core_financ_user_id_0b4470_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal_name', models.CharField(max_length=200)),
                ('goal_type', models.CharField(choices=[('emergency_fund', 'Emergency Fund'), ('retirement', 'Retirement'), ('vacation', 'Vacation'), ('house', 'House Purchase'), ('education', 'Education'), ('debt_payoff', 'Debt Payoff'), ('investment', 'Investment Growth'), ('other', 'Other')], max_length=50)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target_date', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'target_date'],
                'indexes': [models.Index(fields=['user', 'is_achieved'], name='core_financ_user_id_4764ff_idx'), models.Index(fields=['goal_type'], name='core_financ_goal_ty_e4fcc2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('bond', 'Bond'), ('etf', 'ETF'), ('mutual_fund', 'Mutual Fund'), ('crypto', 'Cryptocurrency'), ('commodity', 'Commodity'), ('other', 'Other')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='core.investmentaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'symbol'], name='core_invest_account_35f786_idx'), models.Index(fields=['asset_type'], name='core_invest_asset_t_9aee7b_idx')],
            },
        ),
    ]
